### ISSUE TITLE
It is not currently possible to add Wemo Plugs v1

### ISSUE THREAD

**Issue by Scottbee** [homebridge-plugins/homebridge-platform-wemo#180]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by EfficientSetting** [comment]
Is that the one you are talking about? https://www.amazon.com/gp/product/B00BB2MMNE/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

I've been wondering the past few days why this plug doesn't come up, can you give some more details why it's not possible?
