### ISSUE TITLE
need help connecting!-noobie BTW

### ISSUE THREAD

**Issue by hanzala-123** [homebridge-plugins/homebridge-platform-wemo#183]
hi, i am new to using homebridge. I have installed it on my raspberry pi 4 and am facing trouble linking my wemo smart plug to my homebridge configuration. I have a wemo account and thought it would make more sense adding username and password into the configuration. anyways, i cannot connect my wemo plug to my account and do not know how to set it up in the config file.

kind regards, hanzala.
![download](https://user-images.githubusercontent.com/66522609/83946476-11801480-a809-11ea-9a61-6ed8edbb1b1f.jpg)

**Comment by donavanbecker** [comment]
the plugin should just find your plugin. you will have to get it connected to the wemo app first.
