### ISSUE TITLE
Wemo app updated to cloud version, Wemo maker constantly drop out

### ISSUE THREAD

**Issue by wallacepost** [homebridge-plugins/homebridge-platform-wemo#186]
Hi,
Im using Wemo maker for the garage door, since The Wemo app updated to cloud version, Wemo maker constantly drop out, sometimes it appear as connected in Home app but not working, until restart the hoobs hub Or login to the Wemo app, and sometimes it appear no response. But the Wemo plugs works just fine as usual.
Is this something to do with Wemo app?  Or the plugin? Are those Wemo devices still working in locally or through the cloud when conect to the homebridge? Thanks

**Comment by julien94800** [comment]
Hello,

I am using Wemo Maker as garage door too and no problem so far. Everything still working fine. For information, I did not create a Wemo account so for sure it sill works locally. 
From my side, I am not using HOOBS, but the native homebridge version

**Comment by wallacepost** [comment]
i just reset the Maker, hope this can resolve the connection issue.
I just add a sensor to the Maker, it works in most case.

But I wonder if you have the sensor issue like mine???

when the door is opened, then i pressed CLOSE button, but the door for some reason it didn't move "for example it got stuck", & the sensor did NOT contact to each other. In this situation, It still shows the door is closed in the HOME app, but in WEMO app it shows correct status: "sensor not trigged". Is possible to have the closed status in home app updated only if the physical SENSOR TRIGGED ?

Thanks for your time!

![FullSizeRender-1](https://user-images.githubusercontent.com/65918663/87059682-edbb4e80-c24c-11ea-8ada-6313805eecaf.jpeg)
![FullSizeRender](https://user-images.githubusercontent.com/65918663/87059691-f01da880-c24c-11ea-8fcc-87eb83c4e609.jpeg)

**Comment by wallacepost** [comment]
Is there any way to set the default as showing “OPEN”? So It only changed the states as “Closed “ when the sensors contacted , just in case when the gate stuck half way. Thanks
