### ISSUE TITLE
package.json not updated via npm

### ISSUE THREAD

**Issue by humanthrope** [homebridge-plugins/homebridge-platform-wemo#194]
I noticed this error on OS x 10.14 today after updating via homebrew and npm, although it doesn't seem to affect operation.

> The plugin "homebridge-platform-wemo" requires Node version of ^12.0.0 which does not satisfy the current Node version of v14.8.0. You may need to upgrade your installation of Node.

```
$ sw_vers -productVersion
10.14.6

$ node -v
v14.8.0

$ npm -g ll | grep homebridge-platform-wemo@
+-- homebridge-platform-wemo@1.6.0

$ date -r /usr/local/lib/node_modules/homebridge-platform-wemo/package.json
Mon Aug 17 15:47:50 UTC 2020

$ fgrep '"node"' /usr/local/lib/node_modules/homebridge-platform-wemo/package.json
    "node": "^12.0.0"
```

But the git repo shows `"node": ">=12.0.0"`. So I'm guessing that the new package.json wasn't published correctly or I haven't done something correctly like clearing a cache somewhere.

**Comment by donavanbecker** [comment]
that is just a warning message.
