### ISSUE TITLE
Ignored Devices UI Config Error

### ISSUE THREAD

**Issue by zlockhart** [homebridge-plugins/homebridge-platform-wemo#196]
I'm unable to get ignored devices to work through the homebridge ui config. I keep getting the must match pattern error.
<img width="757" alt="Screen Shot 2020-08-26 at 5 37 05 AM" src="https://user-images.githubusercontent.com/36766381/91305951-b2270600-e760-11ea-86d8-fa30f5b42a7c.png">

**Comment by donavanbecker** [comment]
closing to have you fill out the issue template.
